/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'createdBy' : UserId,
  'dueDate' : Time,
  'description' : string,
  'priority' : AssignmentPriority,
  'department' : Department,
}
export type AssignmentPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface AttendanceRecord {
  'total' : bigint,
  'studentId' : UserId,
  'subject' : string,
  'present' : bigint,
}
export type Department = string;
export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'description' : string,
  'department' : string,
}
export interface LeaveRequest {
  'id' : bigint,
  'status' : LeaveStatus,
  'userId' : UserId,
  'toDate' : Time,
  'fromDate' : Time,
  'reason' : string,
}
export type LeaveStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Reminder {
  'id' : bigint,
  'userId' : UserId,
  'text' : string,
  'dueDate' : Time,
  'priority' : ReminderPriority,
}
export type ReminderPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface StudyMaterial {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'link' : string,
  'timestamp' : Time,
  'department' : Department,
  'uploadedBy' : UserId,
}
export type Time = bigint;
export type UserId = string;
export interface UserProfile {
  'id' : UserId,
  'isStaff' : boolean,
  'password' : string,
  'name' : string,
  'department' : [] | [Department],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAssignment' : ActorMethod<
    [string, string, Department, Time, string, UserId, AssignmentPriority],
    boolean
  >,
  'addReminder' : ActorMethod<
    [UserId, string, ReminderPriority, Time],
    boolean
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateUser' : ActorMethod<[string, string], boolean>,
  'createEvent' : ActorMethod<[string, string, Time, string], boolean>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAssignmentsByDepartment' : ActorMethod<[Department], Array<Assignment>>,
  'getAttendance' : ActorMethod<[UserId], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventsByDepartment' : ActorMethod<[string], Array<Event>>,
  'getLeaveRequests' : ActorMethod<[UserId], Array<LeaveRequest>>,
  'getMaterialsByDepartment' : ActorMethod<[Department], Array<StudyMaterial>>,
  'getReminders' : ActorMethod<[UserId], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStaff' : ActorMethod<[string, string, string], boolean>,
  'registerStudent' : ActorMethod<[string, string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLeave' : ActorMethod<[UserId, Time, Time, string], boolean>,
  'updateAttendance' : ActorMethod<[UserId, string, bigint, bigint], boolean>,
  'updateLeaveStatus' : ActorMethod<[bigint, LeaveStatus], boolean>,
  'updateLoginStreak' : ActorMethod<[UserId], bigint>,
  'uploadMaterial' : ActorMethod<
    [string, string, Department, string, UserId],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];