/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Department = IDL.Text;
export const Time = IDL.Int;
export const UserId = IDL.Text;
export const AssignmentPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ReminderPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'isStaff' : IDL.Bool,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'department' : IDL.Opt(Department),
});
export const Assignment = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdBy' : UserId,
  'dueDate' : Time,
  'description' : IDL.Text,
  'priority' : AssignmentPriority,
  'department' : Department,
});
export const AttendanceRecord = IDL.Record({
  'total' : IDL.Nat,
  'studentId' : UserId,
  'subject' : IDL.Text,
  'present' : IDL.Nat,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'department' : IDL.Text,
});
export const LeaveStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LeaveRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeaveStatus,
  'userId' : UserId,
  'toDate' : Time,
  'fromDate' : Time,
  'reason' : IDL.Text,
});
export const StudyMaterial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'link' : IDL.Text,
  'timestamp' : Time,
  'department' : Department,
  'uploadedBy' : UserId,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'text' : IDL.Text,
  'dueDate' : Time,
  'priority' : ReminderPriority,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAssignment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Department,
        Time,
        IDL.Text,
        UserId,
        AssignmentPriority,
      ],
      [IDL.Bool],
      [],
    ),
  'addReminder' : IDL.Func(
      [UserId, IDL.Text, ReminderPriority, Time],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAssignmentsByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getAttendance' : IDL.Func([UserId], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventsByDepartment' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getLeaveRequests' : IDL.Func([UserId], [IDL.Vec(LeaveRequest)], ['query']),
  'getMaterialsByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(StudyMaterial)],
      ['query'],
    ),
  'getReminders' : IDL.Func([UserId], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLeave' : IDL.Func([UserId, Time, Time, IDL.Text], [IDL.Bool], []),
  'updateAttendance' : IDL.Func(
      [UserId, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateLeaveStatus' : IDL.Func([IDL.Nat, LeaveStatus], [IDL.Bool], []),
  'updateLoginStreak' : IDL.Func([UserId], [IDL.Nat], []),
  'uploadMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, Department, IDL.Text, UserId],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Department = IDL.Text;
  const Time = IDL.Int;
  const UserId = IDL.Text;
  const AssignmentPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ReminderPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'isStaff' : IDL.Bool,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'department' : IDL.Opt(Department),
  });
  const Assignment = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdBy' : UserId,
    'dueDate' : Time,
    'description' : IDL.Text,
    'priority' : AssignmentPriority,
    'department' : Department,
  });
  const AttendanceRecord = IDL.Record({
    'total' : IDL.Nat,
    'studentId' : UserId,
    'subject' : IDL.Text,
    'present' : IDL.Nat,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'department' : IDL.Text,
  });
  const LeaveStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LeaveRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeaveStatus,
    'userId' : UserId,
    'toDate' : Time,
    'fromDate' : Time,
    'reason' : IDL.Text,
  });
  const StudyMaterial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'link' : IDL.Text,
    'timestamp' : Time,
    'department' : Department,
    'uploadedBy' : UserId,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'text' : IDL.Text,
    'dueDate' : Time,
    'priority' : ReminderPriority,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAssignment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Department,
          Time,
          IDL.Text,
          UserId,
          AssignmentPriority,
        ],
        [IDL.Bool],
        [],
      ),
    'addReminder' : IDL.Func(
        [UserId, IDL.Text, ReminderPriority, Time],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAssignmentsByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getAttendance' : IDL.Func(
        [UserId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventsByDepartment' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getLeaveRequests' : IDL.Func([UserId], [IDL.Vec(LeaveRequest)], ['query']),
    'getMaterialsByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(StudyMaterial)],
        ['query'],
      ),
    'getReminders' : IDL.Func([UserId], [IDL.Vec(Reminder)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStaff' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLeave' : IDL.Func([UserId, Time, Time, IDL.Text], [IDL.Bool], []),
    'updateAttendance' : IDL.Func(
        [UserId, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateLeaveStatus' : IDL.Func([IDL.Nat, LeaveStatus], [IDL.Bool], []),
    'updateLoginStreak' : IDL.Func([UserId], [IDL.Nat], []),
    'uploadMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, Department, IDL.Text, UserId],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };